tap "blendle/blendle"
tap "dandavison/delta", "https://github.com/dandavison/delta"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "sendgrid-ops/workstation", "git@github.com:sendgrid-ops/homebrew-workstation.git"
brew "aws-keychain"
brew "aws-okta"
brew "python"
brew "aws-shell"
brew "awscli"
brew "bash-completion"
brew "bat"
brew "go"
brew "dep"
brew "diff-so-fancy"
brew "fd"
brew "fzf"
brew "gettext", link: true
brew "git"
brew "hub"
brew "jq"
brew "keychain"
brew "kubernetes-cli", link: false
brew "mtr", link: false
brew "nmap"
brew "node", link: false
brew "python@2"
brew "rbenv"
brew "ripgrep"
brew "speedtest-cli"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "blendle/blendle/kns"
brew "dandavison/delta/git-delta"
brew "github/gh/gh"
cask "alacritty"
cask "atom"
cask "chromedriver"
cask "vagrant"
cask "virtualbox"
