#!/bin/zsh

function emoji() {
  echo $(yes ":$1:" | head -n $2) | tr -d " " | pbcopy
}

# Create a new directory and enter it
function mkd() {
  mkdir -p "$@" && cd "$_";
}

# Determine size of a file or total size of a directory
function fs() {
  if du -b /dev/null > /dev/null 2>&1; then
    local arg=-sbh;
  else
    local arg=-sh;
  fi
  if [[ -n "$@" ]]; then
    du $arg -- "$@";
  else
    du $arg .[^.]* ./*;
  fi;
}

# Create a data URL from a file
function dataurl() {
  local mimeType=$(file -b --mime-type "$1");
  if [[ $mimeType == text/* ]]; then
    mimeType="${mimeType};charset=utf-8";
  fi
  echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

# Syntax-highlight JSON strings or files
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
function json() {
  if [ -t 0 ]; then # argument
    python -mjson.tool <<< "$*" | pygmentize -l javascript;
  else # pipe
    python -mjson.tool | pygmentize -l javascript;
  fi;
}

# UTF-8-encode a string of Unicode symbols
function escape() {
  printf "\\\x%s" $(printf "$@" | xxd -p -c1 -u);
  # print a newline unless we’re piping the output to another program
  if [ -t 1 ]; then
    echo ""; # newline
  fi;
}

function trash () {
  command mv "$@" ~/.Trash;
}

function brewup() {
  echo 'Starting Brew Stuff 🍺'
  brew update
  brew upgrade
  brew cleanup
  brew doctor
  echo 'Brew Stuff is Over 🍺'
}

function brpb {
  current_git_branch="$(git rev-parse --abbrev-ref HEAD)"
  status="$?"

  if [[ "0" -ne "$status" ]]
  then
    exit "$status"
  fi

  echo "$current_git_branch"
  echo -n "$current_git_branch" | pbcopy
}

function howbig() {
  target="$1"

  # disk usage
  #  -c = Display grand total (it's the first token of the last line)
  #  -h = Human readable format
  size=`du -c -h "$target" | tail -1 | awk '{ print $1 }'`

  echo "$target is $size"
}
